name: Build
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: |
        sudo apt update
        sudo apt install nasm
    - name: configure
      run: ./configure --enable-static --disable-avs --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-lsmash --disable-cli
    - name: make
      run: make -j
    - name: ls
      run: ls  -l
    - name: Upload
      uses: actions/upload-artifact@v2
        with:
          path: libx264.a
          name: libx264.a
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Deploy
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: libx264.a
        asset_name: libx264.a
        asset_content_type: application/octet-stream
